package ffmpeg

/*
#include <libavcodec/version.h>
*/
import "C"

const (
	LIBAVCODEC_VERSION_MAJOR = C.LIBAVCODEC_VERSION_MAJOR
	LIBAVCODEC_VERSION_MINOR = C.LIBAVCODEC_VERSION_MINOR
	LIBAVCODEC_VERSION_MICRO = C.LIBAVCODEC_VERSION_MICRO
)
