package ffmpeg

/*
#include <libavdevice/version.h>
*/
import "C"

const (
	LIBAVDEVICE_VERSION_MAJOR = C.LIBAVDEVICE_VERSION_MAJOR
	LIBAVDEVICE_VERSION_MINOR = C.LIBAVDEVICE_VERSION_MINOR
	LIBAVDEVICE_VERSION_MICRO = C.LIBAVDEVICE_VERSION_MICRO
)
