package ffmpeg

/*
#include <libavfilter/version.h>
*/
import "C"

const (
	LIBAVFILTER_VERSION_MAJOR = C.LIBAVFILTER_VERSION_MAJOR
	LIBAVFILTER_VERSION_MINOR = C.LIBAVFILTER_VERSION_MINOR
	LIBAVFILTER_VERSION_MICRO = C.LIBAVFILTER_VERSION_MICRO
)
