package ffmpeg

/*
#include <libavformat/version.h>
*/
import "C"

const (
	LIBAVFORMAT_VERSION_MAJOR = C.LIBAVFORMAT_VERSION_MAJOR
	LIBAVFORMAT_VERSION_MINOR = C.LIBAVFORMAT_VERSION_MINOR
	LIBAVFORMAT_VERSION_MICRO = C.LIBAVFORMAT_VERSION_MICRO
)
