package ffmpeg

/*
#include <libpostproc/version.h>
*/
import "C"

const (
	LIBPOSTPROC_VERSION_MAJOR = C.LIBPOSTPROC_VERSION_MAJOR
	LIBPOSTPROC_VERSION_MINOR = C.LIBPOSTPROC_VERSION_MINOR
	LIBPOSTPROC_VERSION_MICRO = C.LIBPOSTPROC_VERSION_MICRO
)
