package ffmpeg

/*
#include <libswscale/version.h>
*/
import "C"

const (
	LIBSWSCALE_VERSION_MAJOR = C.LIBSWSCALE_VERSION_MAJOR
	LIBSWSCALE_VERSION_MINOR = C.LIBSWSCALE_VERSION_MINOR
	LIBSWSCALE_VERSION_MICRO = C.LIBSWSCALE_VERSION_MICRO
)
